name: Release

on:
  workflow_dispatch:
    inputs:
      release-name:
        type: string
        description: Release name
        required: true

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Create a Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_NAME: ${{ inputs.release-name }}
        with:
          title: ${{ env.RELEASE_NAME }}
